package vista;

import controlador.*;


/**
 * lase que representa la ventana de venta de productos, donde el cliente realiza
 * la compra
 * @author M. Celeste Cancio Vitale
 */
public class VentanaProductos extends javax.swing.JFrame {
    
    ControladorProducto controladorProducto = new ControladorProducto(this);
    

    /**
     * Constructor de la clase
     */
    public VentanaProductos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelRotulo = new javax.swing.JPanel();
        lblElegiProducto = new javax.swing.JLabel();
        lblCazuela1 = new javax.swing.JLabel();
        panelVentanaPpal = new javax.swing.JPanel();
        panelProductos = new javax.swing.JPanel();
        btnCafeConLeche = new javax.swing.JButton();
        btnJugoDeNaranja = new javax.swing.JButton();
        btnMate = new javax.swing.JButton();
        btnTe = new javax.swing.JButton();
        btnLicuadoFrutal = new javax.swing.JButton();
        lblCafeConLeche = new javax.swing.JLabel();
        lblJugoDeNaranja = new javax.swing.JLabel();
        lblMate = new javax.swing.JLabel();
        lblTe = new javax.swing.JLabel();
        lblLicuadoFrutal = new javax.swing.JLabel();
        btnMedialunas = new javax.swing.JButton();
        btnPlatoDeFruta = new javax.swing.JButton();
        btnTortaDelDia = new javax.swing.JButton();
        btnBizcochitos = new javax.swing.JButton();
        btnTostadasFrancesas = new javax.swing.JButton();
        lblPlatoDeFruta = new javax.swing.JLabel();
        lblMedialunas = new javax.swing.JLabel();
        lblTortaDelDia = new javax.swing.JLabel();
        lblBizcochitos = new javax.swing.JLabel();
        lblTostadasFrancesas = new javax.swing.JLabel();
        lblYogurConGranola = new javax.swing.JLabel();
        btnTostado = new javax.swing.JButton();
        lblTostado = new javax.swing.JLabel();
        btnYogurConGranola = new javax.swing.JButton();
        panelSeleccionyBotonComprar = new javax.swing.JPanel();
        panelProductosSeleccionados = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaProductosSeleccionados = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaPrecioProductosSeleccionados = new javax.swing.JTextArea();
        txtSubtotal = new javax.swing.JTextField();
        lblSubtotal = new javax.swing.JLabel();
        panelBotonComprar = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));

        panelRotulo.setFocusCycleRoot(true);
        panelRotulo.setMaximumSize(new java.awt.Dimension(700, 100));
        panelRotulo.setMinimumSize(new java.awt.Dimension(700, 100));
        panelRotulo.setPreferredSize(new java.awt.Dimension(700, 100));
        panelRotulo.setLayout(new java.awt.GridBagLayout());

        lblElegiProducto.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblElegiProducto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblElegiProducto.setText("Elegí tu producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 30);
        panelRotulo.add(lblElegiProducto, gridBagConstraints);

        lblCazuela1.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        lblCazuela1.setForeground(new java.awt.Color(204, 51, 0));
        lblCazuela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cazuela-removebg-preview (1).png"))); // NOI18N
        lblCazuela1.setText("Cazuela");
        lblCazuela1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblCazuela1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCazuela1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblCazuela1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelRotulo.add(lblCazuela1, gridBagConstraints);

        getContentPane().add(panelRotulo, java.awt.BorderLayout.PAGE_START);

        panelVentanaPpal.setAlignmentX(0.0F);
        panelVentanaPpal.setAlignmentY(0.0F);
        panelVentanaPpal.setFocusTraversalPolicyProvider(true);
        panelVentanaPpal.setMaximumSize(new java.awt.Dimension(700, 500));
        panelVentanaPpal.setMinimumSize(new java.awt.Dimension(700, 500));
        panelVentanaPpal.setPreferredSize(new java.awt.Dimension(700, 500));
        panelVentanaPpal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        panelProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelProductos.setFocusCycleRoot(true);
        panelProductos.setMaximumSize(new java.awt.Dimension(400, 500));
        panelProductos.setMinimumSize(new java.awt.Dimension(400, 500));
        panelProductos.setPreferredSize(new java.awt.Dimension(400, 500));
        panelProductos.setVerifyInputWhenFocusTarget(false);
        panelProductos.setLayout(new java.awt.GridBagLayout());

        btnCafeConLeche.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnCafeConLeche.setText("Café con leche");
        btnCafeConLeche.setAlignmentX(0.5F);
        btnCafeConLeche.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCafeConLeche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCafeConLecheActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelProductos.add(btnCafeConLeche, gridBagConstraints);

        btnJugoDeNaranja.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnJugoDeNaranja.setText("Jugo de naranja");
        btnJugoDeNaranja.setAlignmentX(0.5F);
        btnJugoDeNaranja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnJugoDeNaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugoDeNaranjaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelProductos.add(btnJugoDeNaranja, gridBagConstraints);

        btnMate.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnMate.setText("Mate");
        btnMate.setAlignmentX(0.5F);
        btnMate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMate.setMaximumSize(new java.awt.Dimension(100, 20));
        btnMate.setMinimumSize(new java.awt.Dimension(100, 20));
        btnMate.setPreferredSize(new java.awt.Dimension(100, 20));
        btnMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelProductos.add(btnMate, gridBagConstraints);

        btnTe.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnTe.setText("Té");
        btnTe.setAlignmentX(0.5F);
        btnTe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTe.setMaximumSize(new java.awt.Dimension(100, 20));
        btnTe.setMinimumSize(new java.awt.Dimension(100, 20));
        btnTe.setPreferredSize(new java.awt.Dimension(100, 20));
        btnTe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelProductos.add(btnTe, gridBagConstraints);

        btnLicuadoFrutal.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnLicuadoFrutal.setText("Licuado frutal");
        btnLicuadoFrutal.setAlignmentX(0.5F);
        btnLicuadoFrutal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLicuadoFrutal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicuadoFrutalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelProductos.add(btnLicuadoFrutal, gridBagConstraints);

        lblCafeConLeche.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        lblCafeConLeche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCafeConLeche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Café con lechee.jpg"))); // NOI18N
        lblCafeConLeche.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblCafeConLeche.setAlignmentX(0.5F);
        lblCafeConLeche.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblCafeConLeche.setMaximumSize(new java.awt.Dimension(90, 90));
        lblCafeConLeche.setMinimumSize(new java.awt.Dimension(90, 90));
        lblCafeConLeche.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panelProductos.add(lblCafeConLeche, gridBagConstraints);

        lblJugoDeNaranja.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        lblJugoDeNaranja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugoDeNaranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jugo-de-naranja.jpg"))); // NOI18N
        lblJugoDeNaranja.setAlignmentX(0.5F);
        lblJugoDeNaranja.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblJugoDeNaranja.setMaximumSize(new java.awt.Dimension(90, 90));
        lblJugoDeNaranja.setMinimumSize(new java.awt.Dimension(90, 90));
        lblJugoDeNaranja.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelProductos.add(lblJugoDeNaranja, gridBagConstraints);

        lblMate.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        lblMate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mate cuadrado resized.jpg"))); // NOI18N
        lblMate.setAlignmentX(0.5F);
        lblMate.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblMate.setMaximumSize(new java.awt.Dimension(80, 90));
        lblMate.setMinimumSize(new java.awt.Dimension(90, 90));
        lblMate.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panelProductos.add(lblMate, gridBagConstraints);

        lblTe.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        lblTe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/teeee.jpg"))); // NOI18N
        lblTe.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblTe.setAlignmentX(0.5F);
        lblTe.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblTe.setMaximumSize(new java.awt.Dimension(90, 90));
        lblTe.setMinimumSize(new java.awt.Dimension(90, 90));
        lblTe.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panelProductos.add(lblTe, gridBagConstraints);

        lblLicuadoFrutal.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        lblLicuadoFrutal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLicuadoFrutal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/licuado.jpg"))); // NOI18N
        lblLicuadoFrutal.setAlignmentX(0.5F);
        lblLicuadoFrutal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblLicuadoFrutal.setMaximumSize(new java.awt.Dimension(90, 90));
        lblLicuadoFrutal.setMinimumSize(new java.awt.Dimension(90, 90));
        lblLicuadoFrutal.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelProductos.add(lblLicuadoFrutal, gridBagConstraints);

        btnMedialunas.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnMedialunas.setText("Medialunas");
        btnMedialunas.setAlignmentX(0.5F);
        btnMedialunas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMedialunas.setMaximumSize(new java.awt.Dimension(100, 20));
        btnMedialunas.setMinimumSize(new java.awt.Dimension(100, 20));
        btnMedialunas.setPreferredSize(new java.awt.Dimension(100, 20));
        btnMedialunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedialunasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelProductos.add(btnMedialunas, gridBagConstraints);

        btnPlatoDeFruta.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnPlatoDeFruta.setText("Plato de fruta");
        btnPlatoDeFruta.setAlignmentX(0.5F);
        btnPlatoDeFruta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlatoDeFruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlatoDeFrutaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 20, 0);
        panelProductos.add(btnPlatoDeFruta, gridBagConstraints);

        btnTortaDelDia.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnTortaDelDia.setText("Torta del día");
        btnTortaDelDia.setAlignmentX(0.5F);
        btnTortaDelDia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTortaDelDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTortaDelDiaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 20, 0);
        panelProductos.add(btnTortaDelDia, gridBagConstraints);

        btnBizcochitos.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnBizcochitos.setText("Bizcochitos");
        btnBizcochitos.setAlignmentX(0.5F);
        btnBizcochitos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBizcochitos.setMaximumSize(new java.awt.Dimension(100, 20));
        btnBizcochitos.setMinimumSize(new java.awt.Dimension(100, 20));
        btnBizcochitos.setPreferredSize(new java.awt.Dimension(100, 20));
        btnBizcochitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBizcochitosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelProductos.add(btnBizcochitos, gridBagConstraints);

        btnTostadasFrancesas.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnTostadasFrancesas.setText("Tostadas francesas");
        btnTostadasFrancesas.setAlignmentX(0.5F);
        btnTostadasFrancesas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTostadasFrancesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTostadasFrancesasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelProductos.add(btnTostadasFrancesas, gridBagConstraints);

        lblPlatoDeFruta.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        lblPlatoDeFruta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlatoDeFruta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fruta.jpg"))); // NOI18N
        lblPlatoDeFruta.setAlignmentX(0.5F);
        lblPlatoDeFruta.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblPlatoDeFruta.setMaximumSize(new java.awt.Dimension(90, 90));
        lblPlatoDeFruta.setMinimumSize(new java.awt.Dimension(90, 90));
        lblPlatoDeFruta.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelProductos.add(lblPlatoDeFruta, gridBagConstraints);

        lblMedialunas.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        lblMedialunas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedialunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/madialunas2 (1)_1.jpg"))); // NOI18N
        lblMedialunas.setAlignmentX(0.5F);
        lblMedialunas.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblMedialunas.setMaximumSize(new java.awt.Dimension(90, 90));
        lblMedialunas.setMinimumSize(new java.awt.Dimension(90, 90));
        lblMedialunas.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelProductos.add(lblMedialunas, gridBagConstraints);

        lblTortaDelDia.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        lblTortaDelDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTortaDelDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chocotorta peq resized.jpg"))); // NOI18N
        lblTortaDelDia.setAlignmentX(0.5F);
        lblTortaDelDia.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblTortaDelDia.setMaximumSize(new java.awt.Dimension(90, 90));
        lblTortaDelDia.setMinimumSize(new java.awt.Dimension(90, 90));
        lblTortaDelDia.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelProductos.add(lblTortaDelDia, gridBagConstraints);

        lblBizcochitos.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        lblBizcochitos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBizcochitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bizcochitoss resized.jpg"))); // NOI18N
        lblBizcochitos.setAlignmentX(0.5F);
        lblBizcochitos.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblBizcochitos.setMaximumSize(new java.awt.Dimension(90, 90));
        lblBizcochitos.setMinimumSize(new java.awt.Dimension(90, 90));
        lblBizcochitos.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelProductos.add(lblBizcochitos, gridBagConstraints);

        lblTostadasFrancesas.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        lblTostadasFrancesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTostadasFrancesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/French-Toast resized.jpg"))); // NOI18N
        lblTostadasFrancesas.setAlignmentX(0.5F);
        lblTostadasFrancesas.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblTostadasFrancesas.setMaximumSize(new java.awt.Dimension(90, 90));
        lblTostadasFrancesas.setMinimumSize(new java.awt.Dimension(90, 90));
        lblTostadasFrancesas.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelProductos.add(lblTostadasFrancesas, gridBagConstraints);

        lblYogurConGranola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/yogur granola.jpg"))); // NOI18N
        lblYogurConGranola.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblYogurConGranola.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblYogurConGranola.setMaximumSize(new java.awt.Dimension(90, 90));
        lblYogurConGranola.setMinimumSize(new java.awt.Dimension(90, 90));
        lblYogurConGranola.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelProductos.add(lblYogurConGranola, gridBagConstraints);

        btnTostado.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnTostado.setText("Tostado");
        btnTostado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTostado.setMaximumSize(new java.awt.Dimension(100, 20));
        btnTostado.setMinimumSize(new java.awt.Dimension(100, 20));
        btnTostado.setPreferredSize(new java.awt.Dimension(100, 20));
        btnTostado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTostadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 20, 0);
        panelProductos.add(btnTostado, gridBagConstraints);

        lblTostado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tostado.jpg"))); // NOI18N
        lblTostado.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lblTostado.setMaximumSize(new java.awt.Dimension(90, 90));
        lblTostado.setMinimumSize(new java.awt.Dimension(90, 90));
        lblTostado.setPreferredSize(new java.awt.Dimension(90, 90));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelProductos.add(lblTostado, gridBagConstraints);

        btnYogurConGranola.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        btnYogurConGranola.setText("Yogur con granola");
        btnYogurConGranola.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnYogurConGranola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYogurConGranolaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelProductos.add(btnYogurConGranola, gridBagConstraints);

        panelVentanaPpal.add(panelProductos);

        panelSeleccionyBotonComprar.setInheritsPopupMenu(true);
        panelSeleccionyBotonComprar.setMaximumSize(new java.awt.Dimension(300, 500));
        panelSeleccionyBotonComprar.setMinimumSize(new java.awt.Dimension(300, 500));
        panelSeleccionyBotonComprar.setPreferredSize(new java.awt.Dimension(300, 500));
        panelSeleccionyBotonComprar.setLayout(new javax.swing.BoxLayout(panelSeleccionyBotonComprar, javax.swing.BoxLayout.Y_AXIS));

        panelProductosSeleccionados.setMaximumSize(new java.awt.Dimension(300, 380));
        panelProductosSeleccionados.setMinimumSize(new java.awt.Dimension(300, 380));
        panelProductosSeleccionados.setPreferredSize(new java.awt.Dimension(300, 380));
        panelProductosSeleccionados.setLayout(new java.awt.GridBagLayout());

        lblProducto.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProducto.setText("Producto");
        lblProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblProducto.setMaximumSize(new java.awt.Dimension(150, 22));
        lblProducto.setMinimumSize(new java.awt.Dimension(150, 22));
        lblProducto.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelProductosSeleccionados.add(lblProducto, gridBagConstraints);

        lblPrecio.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("Precio (€)");
        lblPrecio.setMaximumSize(new java.awt.Dimension(80, 22));
        lblPrecio.setMinimumSize(new java.awt.Dimension(80, 22));
        lblPrecio.setPreferredSize(new java.awt.Dimension(80, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelProductosSeleccionados.add(lblPrecio, gridBagConstraints);

        jScrollPane3.setBorder(null);
        jScrollPane3.setMaximumSize(new java.awt.Dimension(150, 300));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(150, 300));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(150, 300));

        txtAreaProductosSeleccionados.setBackground(new java.awt.Color(240, 240, 240));
        txtAreaProductosSeleccionados.setColumns(1);
        txtAreaProductosSeleccionados.setFont(new java.awt.Font("Sylfaen", 1, 13)); // NOI18N
        txtAreaProductosSeleccionados.setRows(1);
        txtAreaProductosSeleccionados.setMaximumSize(new java.awt.Dimension(150, 300));
        txtAreaProductosSeleccionados.setMinimumSize(new java.awt.Dimension(150, 300));
        jScrollPane3.setViewportView(txtAreaProductosSeleccionados);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelProductosSeleccionados.add(jScrollPane3, gridBagConstraints);

        jScrollPane4.setBorder(null);
        jScrollPane4.setMaximumSize(new java.awt.Dimension(40, 300));
        jScrollPane4.setMinimumSize(new java.awt.Dimension(40, 300));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(40, 300));

        txtAreaPrecioProductosSeleccionados.setBackground(new java.awt.Color(240, 240, 240));
        txtAreaPrecioProductosSeleccionados.setColumns(1);
        txtAreaPrecioProductosSeleccionados.setFont(new java.awt.Font("Sylfaen", 1, 13)); // NOI18N
        txtAreaPrecioProductosSeleccionados.setRows(1);
        txtAreaPrecioProductosSeleccionados.setMaximumSize(new java.awt.Dimension(40, 300));
        txtAreaPrecioProductosSeleccionados.setMinimumSize(new java.awt.Dimension(40, 300));
        txtAreaPrecioProductosSeleccionados.setPreferredSize(new java.awt.Dimension(40, 300));
        jScrollPane4.setViewportView(txtAreaPrecioProductosSeleccionados);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelProductosSeleccionados.add(jScrollPane4, gridBagConstraints);

        txtSubtotal.setBackground(new java.awt.Color(240, 240, 240));
        txtSubtotal.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtSubtotal.setBorder(null);
        txtSubtotal.setMaximumSize(new java.awt.Dimension(60, 20));
        txtSubtotal.setMinimumSize(new java.awt.Dimension(60, 20));
        txtSubtotal.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelProductosSeleccionados.add(txtSubtotal, gridBagConstraints);

        lblSubtotal.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotal.setText("Subtotal");
        lblSubtotal.setMaximumSize(new java.awt.Dimension(60, 20));
        lblSubtotal.setMinimumSize(new java.awt.Dimension(60, 20));
        lblSubtotal.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelProductosSeleccionados.add(lblSubtotal, gridBagConstraints);

        panelSeleccionyBotonComprar.add(panelProductosSeleccionados);

        panelBotonComprar.setMaximumSize(new java.awt.Dimension(300, 120));
        panelBotonComprar.setMinimumSize(new java.awt.Dimension(300, 120));
        panelBotonComprar.setPreferredSize(new java.awt.Dimension(300, 120));

        btnComprar.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnComprar.setText("COMPRAR");
        btnComprar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnComprar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComprar.setMaximumSize(new java.awt.Dimension(130, 90));
        btnComprar.setMinimumSize(new java.awt.Dimension(130, 90));
        btnComprar.setPreferredSize(new java.awt.Dimension(130, 90));
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        panelBotonComprar.add(btnComprar);

        panelSeleccionyBotonComprar.add(panelBotonComprar);

        panelVentanaPpal.add(panelSeleccionyBotonComprar);

        getContentPane().add(panelVentanaPpal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCafeConLecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCafeConLecheActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnCafeConLecheActionPerformed

    private void btnTeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnTeActionPerformed

    private void btnMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnMateActionPerformed

    private void btnLicuadoFrutalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicuadoFrutalActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnLicuadoFrutalActionPerformed

    private void btnJugoDeNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugoDeNaranjaActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnJugoDeNaranjaActionPerformed

    private void btnYogurConGranolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYogurConGranolaActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnYogurConGranolaActionPerformed

    private void btnMedialunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedialunasActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnMedialunasActionPerformed

    private void btnTostadasFrancesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTostadasFrancesasActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnTostadasFrancesasActionPerformed

    private void btnBizcochitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBizcochitosActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnBizcochitosActionPerformed

    private void btnPlatoDeFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlatoDeFrutaActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnPlatoDeFrutaActionPerformed

    private void btnTortaDelDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTortaDelDiaActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnTortaDelDiaActionPerformed

    private void btnTostadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTostadoActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnTostadoActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        controladorProducto.actionPerformed(evt);
    }//GEN-LAST:event_btnComprarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaProductos().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBizcochitos;
    public javax.swing.JButton btnCafeConLeche;
    public javax.swing.JButton btnComprar;
    public javax.swing.JButton btnJugoDeNaranja;
    public javax.swing.JButton btnLicuadoFrutal;
    public javax.swing.JButton btnMate;
    public javax.swing.JButton btnMedialunas;
    public javax.swing.JButton btnPlatoDeFruta;
    public javax.swing.JButton btnTe;
    public javax.swing.JButton btnTortaDelDia;
    public javax.swing.JButton btnTostadasFrancesas;
    public javax.swing.JButton btnTostado;
    public javax.swing.JButton btnYogurConGranola;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblBizcochitos;
    private javax.swing.JLabel lblCafeConLeche;
    private javax.swing.JLabel lblCazuela1;
    private javax.swing.JLabel lblElegiProducto;
    private javax.swing.JLabel lblJugoDeNaranja;
    private javax.swing.JLabel lblLicuadoFrutal;
    private javax.swing.JLabel lblMate;
    private javax.swing.JLabel lblMedialunas;
    private javax.swing.JLabel lblPlatoDeFruta;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTe;
    private javax.swing.JLabel lblTortaDelDia;
    private javax.swing.JLabel lblTostadasFrancesas;
    private javax.swing.JLabel lblTostado;
    private javax.swing.JLabel lblYogurConGranola;
    private javax.swing.JPanel panelBotonComprar;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelProductosSeleccionados;
    private javax.swing.JPanel panelRotulo;
    private javax.swing.JPanel panelSeleccionyBotonComprar;
    private javax.swing.JPanel panelVentanaPpal;
    public javax.swing.JTextArea txtAreaPrecioProductosSeleccionados;
    public javax.swing.JTextArea txtAreaProductosSeleccionados;
    public javax.swing.JTextField txtSubtotal;
    // End of variables declaration//GEN-END:variables
}
