package vista;

import controlador.ControladorConsultaEmpleados;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JInternalFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelo.ConexionBBDD;

/**
 * Clase que representa la ventana en la cual los empleados realizan consultas
 * @author M. Celeste Cancio Vitale
 */
public class VentanaConsultaEmpleados extends javax.swing.JFrame {
    
    ControladorConsultaEmpleados controladorConsultaEmpleados = new ControladorConsultaEmpleados(this);

    /**
     * Constructor de la clase
     */
    public VentanaConsultaEmpleados() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.internalFrameTablaProductosEnVenta.setVisible(false);
        this.internalFrameClientesRegistrados.setVisible(false);
        this.internalFrameVentasTotales.setVisible(false);
        this.internalFrameVentasPorDiaJComboBox.setVisible(false);
        this.internalFrameVentasPorDiaTabla.setVisible(false);
        this.internalFrameInsertarCliente.setVisible(false);
        this.internalFrameEditarCliente.setVisible(false);
        this.internalFrameEliminarCliente.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        internalFrameClientesRegistrados = new javax.swing.JInternalFrame();
        panelTablaClientesRegistrados = new javax.swing.JPanel();
        panelScrollTablaClientesRegistrados = new javax.swing.JScrollPane();
        tablaClientesRegistrados = new javax.swing.JTable();
        internalFrameTablaProductosEnVenta = new javax.swing.JInternalFrame();
        panelTablaProductosEnVenta = new javax.swing.JPanel();
        panelScrollTablaProductosEnVenta = new javax.swing.JScrollPane();
        tablaProductosEnVenta = new javax.swing.JTable();
        internalFrameVentasTotales = new javax.swing.JInternalFrame();
        panelTablaVentasTotales = new javax.swing.JPanel();
        panelScrollTablaVentasTotales = new javax.swing.JScrollPane();
        tablaVentasTotales = new javax.swing.JTable();
        internalFrameVentasPorDiaJComboBox = new javax.swing.JInternalFrame();
        panelVentasPorDiaJComboBox = new javax.swing.JPanel();
        jComboBoxFechasVentas = new javax.swing.JComboBox<>();
        lblFechas = new javax.swing.JLabel();
        internalFrameVentasPorDiaTabla = new javax.swing.JInternalFrame();
        panelTablaVentasPorDiaTabla = new javax.swing.JPanel();
        panelScrollTablaVentasPorDiaTabla = new javax.swing.JScrollPane();
        tablaVentasPorDia = new javax.swing.JTable();
        internalFrameInsertarCliente = new javax.swing.JInternalFrame();
        panelInsertarClientes = new javax.swing.JPanel();
        panelDatosNuevoCliente = new javax.swing.JPanel();
        lblDatosNuevoCliente = new javax.swing.JLabel();
        lblNombreNuevoCliente = new javax.swing.JLabel();
        txtNombreNuevoCliente = new javax.swing.JTextField();
        lblApellido1NuevoCliente = new javax.swing.JLabel();
        txtApellido1NuevoCliente = new javax.swing.JTextField();
        lblApellido2NuevoCliente = new javax.swing.JLabel();
        txtApellido2NuevoCliente = new javax.swing.JTextField();
        lblTelefonoNuevoCliente = new javax.swing.JLabel();
        txtTelefonoNuevoCliente = new javax.swing.JTextField();
        btnObtenerUsuario = new javax.swing.JButton();
        lblUsuarioNuevoCliente = new javax.swing.JLabel();
        txtUsuarioNuevoCliente = new javax.swing.JTextField();
        btnIngresarNuevoCliente = new javax.swing.JButton();
        internalFrameEditarCliente = new javax.swing.JInternalFrame();
        panelEditarClientes = new javax.swing.JPanel();
        panelDatosClienteEditar = new javax.swing.JPanel();
        lblUsuarioClienteEditar = new javax.swing.JLabel();
        txtUsuarioClienteEditar = new javax.swing.JTextField();
        lblDatosClienteEditar = new javax.swing.JLabel();
        lblNombreClienteEditar = new javax.swing.JLabel();
        txtNombreClienteEditar = new javax.swing.JTextField();
        lblApellido1ClienteEditar = new javax.swing.JLabel();
        txtApellido1ClienteEditar = new javax.swing.JTextField();
        lblApellido2ClienteEditar = new javax.swing.JLabel();
        txtApellido2ClienteEditar = new javax.swing.JTextField();
        lblTelefonoClienteEditar = new javax.swing.JLabel();
        txtTelefonoClienteEditar = new javax.swing.JTextField();
        btnIngresarClienteEditar = new javax.swing.JButton();
        internalFrameEliminarCliente = new javax.swing.JInternalFrame();
        panelEliminarClientes = new javax.swing.JPanel();
        panelEliminarCliente = new javax.swing.JPanel();
        lblDatosClienteEliminar = new javax.swing.JLabel();
        lblUsuarioClienteEliminar = new javax.swing.JLabel();
        txtUsuarioClienteEliminar = new javax.swing.JTextField();
        lblNombreClienteEliminar = new javax.swing.JLabel();
        txtNombreClienteEliminar = new javax.swing.JTextField();
        lblApellido1ClienteEliminar = new javax.swing.JLabel();
        txtApellido1ClienteEliminar = new javax.swing.JTextField();
        lblApellido2ClienteEliminar = new javax.swing.JLabel();
        txtApellido2ClienteEliminar = new javax.swing.JTextField();
        lblTelefonoClienteEliminar = new javax.swing.JLabel();
        txtTelefonoClienteEliminar = new javax.swing.JTextField();
        btnEliminarCliente = new javax.swing.JButton();
        mnuBVentanaGestionEmpleados = new javax.swing.JMenuBar();
        mnuProductos = new javax.swing.JMenu();
        mnuIProductosEnVenta = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        mnuIClientesRegistrados = new javax.swing.JMenuItem();
        mnuIRegistrarNuevoCliente = new javax.swing.JMenuItem();
        mnuIModificarCliente = new javax.swing.JMenuItem();
        mnuIEliminarCliente = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mnuIVentasPorDia = new javax.swing.JMenuItem();
        mnuIVentasTotales = new javax.swing.JMenuItem();
        mnuMenu = new javax.swing.JMenu();
        mnuIVentanaIngreso = new javax.swing.JMenuItem();
        mnuISalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cazuela");
        setResizable(false);

        jDesktopPane.setBackground(new java.awt.Color(240, 240, 240));
        jDesktopPane.setForeground(new java.awt.Color(240, 240, 240));
        jDesktopPane.setMaximumSize(new java.awt.Dimension(700, 472));
        jDesktopPane.setMinimumSize(new java.awt.Dimension(700, 472));
        jDesktopPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        internalFrameClientesRegistrados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        internalFrameClientesRegistrados.setClosable(true);
        internalFrameClientesRegistrados.setTitle("Tabla Clientes Registrados");
        internalFrameClientesRegistrados.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        internalFrameClientesRegistrados.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cazuela-30.png"))); // NOI18N
        internalFrameClientesRegistrados.setMaximumSize(new java.awt.Dimension(720, 472));
        internalFrameClientesRegistrados.setMinimumSize(new java.awt.Dimension(720, 472));
        internalFrameClientesRegistrados.setPreferredSize(new java.awt.Dimension(720, 472));
        internalFrameClientesRegistrados.setVisible(true);
        internalFrameClientesRegistrados.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTablaClientesRegistrados.setMaximumSize(new java.awt.Dimension(700, 440));
        panelTablaClientesRegistrados.setMinimumSize(new java.awt.Dimension(700, 440));
        panelTablaClientesRegistrados.setLayout(new java.awt.BorderLayout());

        tablaClientesRegistrados.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        tablaClientesRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Nombre", "Apellido1", "Apellido2", "Telefono", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientesRegistrados.setMaximumSize(new java.awt.Dimension(600, 350));
        tablaClientesRegistrados.setMinimumSize(new java.awt.Dimension(600, 350));
        tablaClientesRegistrados.setPreferredSize(new java.awt.Dimension(600, 350));
        panelScrollTablaClientesRegistrados.setViewportView(tablaClientesRegistrados);
        if (tablaClientesRegistrados.getColumnModel().getColumnCount() > 0) {
            tablaClientesRegistrados.getColumnModel().getColumn(0).setMinWidth(70);
            tablaClientesRegistrados.getColumnModel().getColumn(0).setPreferredWidth(70);
            tablaClientesRegistrados.getColumnModel().getColumn(0).setMaxWidth(70);
            tablaClientesRegistrados.getColumnModel().getColumn(5).setMinWidth(180);
            tablaClientesRegistrados.getColumnModel().getColumn(5).setPreferredWidth(180);
            tablaClientesRegistrados.getColumnModel().getColumn(5).setMaxWidth(180);
        }

        panelTablaClientesRegistrados.add(panelScrollTablaClientesRegistrados, java.awt.BorderLayout.CENTER);

        internalFrameClientesRegistrados.getContentPane().add(panelTablaClientesRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 700, 374));

        jDesktopPane.add(internalFrameClientesRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        internalFrameTablaProductosEnVenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        internalFrameTablaProductosEnVenta.setClosable(true);
        internalFrameTablaProductosEnVenta.setTitle("Tabla Productos en venta");
        internalFrameTablaProductosEnVenta.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        internalFrameTablaProductosEnVenta.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cazuela-30.png"))); // NOI18N
        internalFrameTablaProductosEnVenta.setMaximumSize(new java.awt.Dimension(720, 472));
        internalFrameTablaProductosEnVenta.setMinimumSize(new java.awt.Dimension(720, 472));
        internalFrameTablaProductosEnVenta.setPreferredSize(new java.awt.Dimension(720, 472));
        internalFrameTablaProductosEnVenta.setVisible(true);
        internalFrameTablaProductosEnVenta.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTablaProductosEnVenta.setMaximumSize(new java.awt.Dimension(700, 440));
        panelTablaProductosEnVenta.setMinimumSize(new java.awt.Dimension(700, 440));
        panelTablaProductosEnVenta.setPreferredSize(new java.awt.Dimension(700, 440));
        panelTablaProductosEnVenta.setLayout(new java.awt.BorderLayout());

        tablaProductosEnVenta.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        tablaProductosEnVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CodigoProducto", "NombreProducto", "PrecioProducto", "AliasProducto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductosEnVenta.setMaximumSize(new java.awt.Dimension(600, 350));
        tablaProductosEnVenta.setMinimumSize(new java.awt.Dimension(600, 350));
        tablaProductosEnVenta.setPreferredSize(new java.awt.Dimension(600, 350));
        panelScrollTablaProductosEnVenta.setViewportView(tablaProductosEnVenta);
        if (tablaProductosEnVenta.getColumnModel().getColumnCount() > 0) {
            tablaProductosEnVenta.getColumnModel().getColumn(0).setMinWidth(100);
            tablaProductosEnVenta.getColumnModel().getColumn(0).setPreferredWidth(100);
            tablaProductosEnVenta.getColumnModel().getColumn(0).setMaxWidth(100);
            tablaProductosEnVenta.getColumnModel().getColumn(2).setMinWidth(100);
            tablaProductosEnVenta.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaProductosEnVenta.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        panelTablaProductosEnVenta.add(panelScrollTablaProductosEnVenta, java.awt.BorderLayout.CENTER);

        internalFrameTablaProductosEnVenta.getContentPane().add(panelTablaProductosEnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 700, 374));

        jDesktopPane.add(internalFrameTablaProductosEnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        internalFrameVentasTotales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        internalFrameVentasTotales.setClosable(true);
        internalFrameVentasTotales.setTitle("Tabla Ventas Totales");
        internalFrameVentasTotales.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cazuela-30.png"))); // NOI18N
        internalFrameVentasTotales.setMaximumSize(new java.awt.Dimension(720, 472));
        internalFrameVentasTotales.setMinimumSize(new java.awt.Dimension(720, 472));
        internalFrameVentasTotales.setPreferredSize(new java.awt.Dimension(720, 472));
        internalFrameVentasTotales.setVisible(true);

        panelTablaVentasTotales.setMaximumSize(new java.awt.Dimension(700, 440));
        panelTablaVentasTotales.setMinimumSize(new java.awt.Dimension(700, 440));
        panelTablaVentasTotales.setPreferredSize(new java.awt.Dimension(700, 440));
        panelTablaVentasTotales.setLayout(new java.awt.BorderLayout());

        panelScrollTablaVentasTotales.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        panelScrollTablaVentasTotales.setAutoscrolls(true);
        panelScrollTablaVentasTotales.setPreferredSize(new java.awt.Dimension(452, 402));

        tablaVentasTotales.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        tablaVentasTotales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IDVenta", "NombreProducto", "PrecioProducto", "AliasProducto", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentasTotales.setMaximumSize(new java.awt.Dimension(600, 350));
        tablaVentasTotales.setMinimumSize(new java.awt.Dimension(600, 350));
        tablaVentasTotales.setPreferredSize(new java.awt.Dimension(600, 350));
        panelScrollTablaVentasTotales.setViewportView(tablaVentasTotales);
        if (tablaVentasTotales.getColumnModel().getColumnCount() > 0) {
            tablaVentasTotales.getColumnModel().getColumn(0).setMinWidth(70);
            tablaVentasTotales.getColumnModel().getColumn(0).setPreferredWidth(70);
            tablaVentasTotales.getColumnModel().getColumn(0).setMaxWidth(70);
            tablaVentasTotales.getColumnModel().getColumn(2).setMinWidth(100);
            tablaVentasTotales.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaVentasTotales.getColumnModel().getColumn(2).setMaxWidth(70100);
        }

        panelTablaVentasTotales.add(panelScrollTablaVentasTotales, java.awt.BorderLayout.CENTER);

        internalFrameVentasTotales.getContentPane().add(panelTablaVentasTotales, java.awt.BorderLayout.CENTER);

        jDesktopPane.add(internalFrameVentasTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        internalFrameVentasPorDiaJComboBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        internalFrameVentasPorDiaJComboBox.setClosable(true);
        internalFrameVentasPorDiaJComboBox.setTitle("Selección fecha - Ventas por día");
        internalFrameVentasPorDiaJComboBox.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cazuela-30.png"))); // NOI18N
        internalFrameVentasPorDiaJComboBox.setMaximumSize(new java.awt.Dimension(720, 472));
        internalFrameVentasPorDiaJComboBox.setMinimumSize(new java.awt.Dimension(720, 472));
        internalFrameVentasPorDiaJComboBox.setPreferredSize(new java.awt.Dimension(720, 472));
        internalFrameVentasPorDiaJComboBox.setVisible(true);

        panelVentasPorDiaJComboBox.setMaximumSize(new java.awt.Dimension(716, 411));
        panelVentasPorDiaJComboBox.setMinimumSize(new java.awt.Dimension(716, 411));
        panelVentasPorDiaJComboBox.setPreferredSize(new java.awt.Dimension(716, 411));

        jComboBoxFechasVentas.setBackground(new java.awt.Color(240, 240, 240));
        jComboBoxFechasVentas.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jComboBoxFechasVentas.setMaximumSize(new java.awt.Dimension(120, 30));
        jComboBoxFechasVentas.setMinimumSize(new java.awt.Dimension(120, 30));
        jComboBoxFechasVentas.setPreferredSize(new java.awt.Dimension(120, 30));
        jComboBoxFechasVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFechasVentasActionPerformed(evt);
            }
        });

        lblFechas.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        lblFechas.setText("Fecha");
        lblFechas.setMaximumSize(new java.awt.Dimension(50, 30));
        lblFechas.setMinimumSize(new java.awt.Dimension(50, 30));
        lblFechas.setPreferredSize(new java.awt.Dimension(50, 30));

        javax.swing.GroupLayout panelVentasPorDiaJComboBoxLayout = new javax.swing.GroupLayout(panelVentasPorDiaJComboBox);
        panelVentasPorDiaJComboBox.setLayout(panelVentasPorDiaJComboBoxLayout);
        panelVentasPorDiaJComboBoxLayout.setHorizontalGroup(
            panelVentasPorDiaJComboBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasPorDiaJComboBoxLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(lblFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFechasVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        panelVentasPorDiaJComboBoxLayout.setVerticalGroup(
            panelVentasPorDiaJComboBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasPorDiaJComboBoxLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelVentasPorDiaJComboBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFechasVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(359, Short.MAX_VALUE))
        );

        internalFrameVentasPorDiaJComboBox.getContentPane().add(panelVentasPorDiaJComboBox, java.awt.BorderLayout.CENTER);

        jDesktopPane.add(internalFrameVentasPorDiaJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        internalFrameVentasPorDiaTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        internalFrameVentasPorDiaTabla.setClosable(true);
        internalFrameVentasPorDiaTabla.setTitle("Tabla Ventas por día");
        internalFrameVentasPorDiaTabla.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cazuela-30.png"))); // NOI18N
        internalFrameVentasPorDiaTabla.setMaximumSize(new java.awt.Dimension(720, 472));
        internalFrameVentasPorDiaTabla.setMinimumSize(new java.awt.Dimension(720, 472));
        internalFrameVentasPorDiaTabla.setPreferredSize(new java.awt.Dimension(720, 472));
        internalFrameVentasPorDiaTabla.setVisible(true);
        internalFrameVentasPorDiaTabla.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTablaVentasPorDiaTabla.setMaximumSize(new java.awt.Dimension(716, 411));
        panelTablaVentasPorDiaTabla.setMinimumSize(new java.awt.Dimension(716, 411));

        panelScrollTablaVentasPorDiaTabla.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        panelScrollTablaVentasPorDiaTabla.setPreferredSize(new java.awt.Dimension(452, 402));

        tablaVentasPorDia.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        tablaVentasPorDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IDVenta", "NombreProducto", "PrecioProducto", "AliasProducto", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentasPorDia.setMaximumSize(new java.awt.Dimension(600, 350));
        tablaVentasPorDia.setMinimumSize(new java.awt.Dimension(600, 350));
        tablaVentasPorDia.setPreferredSize(new java.awt.Dimension(600, 350));
        panelScrollTablaVentasPorDiaTabla.setViewportView(tablaVentasPorDia);
        if (tablaVentasPorDia.getColumnModel().getColumnCount() > 0) {
            tablaVentasPorDia.getColumnModel().getColumn(0).setMinWidth(70);
            tablaVentasPorDia.getColumnModel().getColumn(0).setPreferredWidth(70);
            tablaVentasPorDia.getColumnModel().getColumn(0).setMaxWidth(70);
            tablaVentasPorDia.getColumnModel().getColumn(2).setMinWidth(100);
            tablaVentasPorDia.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaVentasPorDia.getColumnModel().getColumn(2).setMaxWidth(70100);
        }

        javax.swing.GroupLayout panelTablaVentasPorDiaTablaLayout = new javax.swing.GroupLayout(panelTablaVentasPorDiaTabla);
        panelTablaVentasPorDiaTabla.setLayout(panelTablaVentasPorDiaTablaLayout);
        panelTablaVentasPorDiaTablaLayout.setHorizontalGroup(
            panelTablaVentasPorDiaTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaVentasPorDiaTablaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelScrollTablaVentasPorDiaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelTablaVentasPorDiaTablaLayout.setVerticalGroup(
            panelTablaVentasPorDiaTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaVentasPorDiaTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelScrollTablaVentasPorDiaTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        internalFrameVentasPorDiaTabla.getContentPane().add(panelTablaVentasPorDiaTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jDesktopPane.add(internalFrameVentasPorDiaTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        internalFrameInsertarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        internalFrameInsertarCliente.setClosable(true);
        internalFrameInsertarCliente.setTitle("Insertar nuevo cliente");
        internalFrameInsertarCliente.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cazuela-30.png"))); // NOI18N
        internalFrameInsertarCliente.setMaximumSize(new java.awt.Dimension(720, 472));
        internalFrameInsertarCliente.setMinimumSize(new java.awt.Dimension(720, 472));
        internalFrameInsertarCliente.setPreferredSize(new java.awt.Dimension(720, 472));
        internalFrameInsertarCliente.setVisible(true);
        internalFrameInsertarCliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInsertarClientes.setMaximumSize(new java.awt.Dimension(700, 440));
        panelInsertarClientes.setMinimumSize(new java.awt.Dimension(700, 440));

        panelDatosNuevoCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDatosNuevoCliente.setMaximumSize(new java.awt.Dimension(400, 300));
        panelDatosNuevoCliente.setMinimumSize(new java.awt.Dimension(400, 300));
        panelDatosNuevoCliente.setPreferredSize(new java.awt.Dimension(400, 300));
        panelDatosNuevoCliente.setRequestFocusEnabled(false);
        panelDatosNuevoCliente.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lblDatosNuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblDatosNuevoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatosNuevoCliente.setText("DATOS DEL NUEVO CLIENTE");
        lblDatosNuevoCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDatosNuevoCliente.setMaximumSize(new java.awt.Dimension(300, 24));
        lblDatosNuevoCliente.setMinimumSize(new java.awt.Dimension(300, 24));
        lblDatosNuevoCliente.setPreferredSize(new java.awt.Dimension(300, 24));
        panelDatosNuevoCliente.add(lblDatosNuevoCliente);

        lblNombreNuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblNombreNuevoCliente.setText("Nombre ");
        lblNombreNuevoCliente.setMaximumSize(new java.awt.Dimension(150, 20));
        lblNombreNuevoCliente.setMinimumSize(new java.awt.Dimension(150, 20));
        lblNombreNuevoCliente.setPreferredSize(new java.awt.Dimension(150, 20));
        panelDatosNuevoCliente.add(lblNombreNuevoCliente);

        txtNombreNuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtNombreNuevoCliente.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtNombreNuevoCliente.setMaximumSize(new java.awt.Dimension(170, 25));
        txtNombreNuevoCliente.setMinimumSize(new java.awt.Dimension(170, 25));
        txtNombreNuevoCliente.setPreferredSize(new java.awt.Dimension(170, 25));
        panelDatosNuevoCliente.add(txtNombreNuevoCliente);

        lblApellido1NuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblApellido1NuevoCliente.setText("Apellido 1");
        lblApellido1NuevoCliente.setMaximumSize(new java.awt.Dimension(150, 20));
        lblApellido1NuevoCliente.setMinimumSize(new java.awt.Dimension(150, 20));
        lblApellido1NuevoCliente.setPreferredSize(new java.awt.Dimension(150, 20));
        panelDatosNuevoCliente.add(lblApellido1NuevoCliente);

        txtApellido1NuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtApellido1NuevoCliente.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtApellido1NuevoCliente.setMaximumSize(new java.awt.Dimension(170, 25));
        txtApellido1NuevoCliente.setMinimumSize(new java.awt.Dimension(170, 25));
        txtApellido1NuevoCliente.setPreferredSize(new java.awt.Dimension(170, 25));
        panelDatosNuevoCliente.add(txtApellido1NuevoCliente);

        lblApellido2NuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblApellido2NuevoCliente.setText("Apellido 2");
        lblApellido2NuevoCliente.setMaximumSize(new java.awt.Dimension(150, 20));
        lblApellido2NuevoCliente.setMinimumSize(new java.awt.Dimension(150, 20));
        lblApellido2NuevoCliente.setPreferredSize(new java.awt.Dimension(150, 20));
        panelDatosNuevoCliente.add(lblApellido2NuevoCliente);

        txtApellido2NuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtApellido2NuevoCliente.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtApellido2NuevoCliente.setMaximumSize(new java.awt.Dimension(170, 25));
        txtApellido2NuevoCliente.setMinimumSize(new java.awt.Dimension(170, 25));
        txtApellido2NuevoCliente.setPreferredSize(new java.awt.Dimension(170, 25));
        panelDatosNuevoCliente.add(txtApellido2NuevoCliente);

        lblTelefonoNuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblTelefonoNuevoCliente.setText("Teléfono");
        lblTelefonoNuevoCliente.setMaximumSize(new java.awt.Dimension(150, 20));
        lblTelefonoNuevoCliente.setMinimumSize(new java.awt.Dimension(150, 20));
        lblTelefonoNuevoCliente.setPreferredSize(new java.awt.Dimension(150, 20));
        panelDatosNuevoCliente.add(lblTelefonoNuevoCliente);

        txtTelefonoNuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtTelefonoNuevoCliente.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtTelefonoNuevoCliente.setMaximumSize(new java.awt.Dimension(170, 25));
        txtTelefonoNuevoCliente.setMinimumSize(new java.awt.Dimension(170, 25));
        txtTelefonoNuevoCliente.setPreferredSize(new java.awt.Dimension(170, 25));
        panelDatosNuevoCliente.add(txtTelefonoNuevoCliente);

        btnObtenerUsuario.setFont(new java.awt.Font("Sylfaen", 1, 10)); // NOI18N
        btnObtenerUsuario.setText("OBTENER USUARIO");
        btnObtenerUsuario.setMaximumSize(new java.awt.Dimension(200, 25));
        btnObtenerUsuario.setMinimumSize(new java.awt.Dimension(200, 25));
        btnObtenerUsuario.setPreferredSize(new java.awt.Dimension(200, 25));
        btnObtenerUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerUsuarioActionPerformed(evt);
            }
        });
        panelDatosNuevoCliente.add(btnObtenerUsuario);

        lblUsuarioNuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblUsuarioNuevoCliente.setText("Usuario");
        lblUsuarioNuevoCliente.setMaximumSize(new java.awt.Dimension(150, 20));
        lblUsuarioNuevoCliente.setMinimumSize(new java.awt.Dimension(150, 20));
        lblUsuarioNuevoCliente.setPreferredSize(new java.awt.Dimension(150, 20));
        panelDatosNuevoCliente.add(lblUsuarioNuevoCliente);

        txtUsuarioNuevoCliente.setEditable(false);
        txtUsuarioNuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtUsuarioNuevoCliente.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtUsuarioNuevoCliente.setMaximumSize(new java.awt.Dimension(170, 25));
        txtUsuarioNuevoCliente.setMinimumSize(new java.awt.Dimension(170, 25));
        txtUsuarioNuevoCliente.setPreferredSize(new java.awt.Dimension(170, 25));
        panelDatosNuevoCliente.add(txtUsuarioNuevoCliente);

        btnIngresarNuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        btnIngresarNuevoCliente.setText("INGRESAR");
        btnIngresarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarNuevoClienteActionPerformed(evt);
            }
        });
        panelDatosNuevoCliente.add(btnIngresarNuevoCliente);

        javax.swing.GroupLayout panelInsertarClientesLayout = new javax.swing.GroupLayout(panelInsertarClientes);
        panelInsertarClientes.setLayout(panelInsertarClientesLayout);
        panelInsertarClientesLayout.setHorizontalGroup(
            panelInsertarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertarClientesLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(panelDatosNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        panelInsertarClientesLayout.setVerticalGroup(
            panelInsertarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertarClientesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(panelDatosNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        internalFrameInsertarCliente.getContentPane().add(panelInsertarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 411));

        jDesktopPane.add(internalFrameInsertarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        internalFrameEditarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        internalFrameEditarCliente.setClosable(true);
        internalFrameEditarCliente.setTitle("Eliminar cliente");
        internalFrameEditarCliente.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cazuela-30.png"))); // NOI18N
        internalFrameEditarCliente.setMaximumSize(new java.awt.Dimension(720, 472));
        internalFrameEditarCliente.setMinimumSize(new java.awt.Dimension(720, 472));
        internalFrameEditarCliente.setPreferredSize(new java.awt.Dimension(720, 472));
        internalFrameEditarCliente.setVisible(true);
        internalFrameEditarCliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEditarClientes.setMaximumSize(new java.awt.Dimension(700, 440));
        panelEditarClientes.setMinimumSize(new java.awt.Dimension(700, 440));

        panelDatosClienteEditar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDatosClienteEditar.setMaximumSize(new java.awt.Dimension(400, 300));
        panelDatosClienteEditar.setMinimumSize(new java.awt.Dimension(400, 300));
        panelDatosClienteEditar.setPreferredSize(new java.awt.Dimension(400, 300));
        panelDatosClienteEditar.setRequestFocusEnabled(false);
        panelDatosClienteEditar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lblUsuarioClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblUsuarioClienteEditar.setText("Usuario");
        lblUsuarioClienteEditar.setMaximumSize(new java.awt.Dimension(150, 20));
        lblUsuarioClienteEditar.setMinimumSize(new java.awt.Dimension(150, 20));
        lblUsuarioClienteEditar.setPreferredSize(new java.awt.Dimension(150, 20));
        panelDatosClienteEditar.add(lblUsuarioClienteEditar);

        txtUsuarioClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtUsuarioClienteEditar.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtUsuarioClienteEditar.setMaximumSize(new java.awt.Dimension(170, 25));
        txtUsuarioClienteEditar.setMinimumSize(new java.awt.Dimension(170, 25));
        txtUsuarioClienteEditar.setPreferredSize(new java.awt.Dimension(170, 25));
        panelDatosClienteEditar.add(txtUsuarioClienteEditar);

        lblDatosClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblDatosClienteEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatosClienteEditar.setText("DATOS A EDITAR");
        lblDatosClienteEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDatosClienteEditar.setMaximumSize(new java.awt.Dimension(300, 24));
        lblDatosClienteEditar.setMinimumSize(new java.awt.Dimension(300, 24));
        lblDatosClienteEditar.setPreferredSize(new java.awt.Dimension(300, 24));
        panelDatosClienteEditar.add(lblDatosClienteEditar);

        lblNombreClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblNombreClienteEditar.setText("Nombre corregido");
        lblNombreClienteEditar.setMaximumSize(new java.awt.Dimension(150, 20));
        lblNombreClienteEditar.setMinimumSize(new java.awt.Dimension(150, 20));
        lblNombreClienteEditar.setPreferredSize(new java.awt.Dimension(150, 20));
        panelDatosClienteEditar.add(lblNombreClienteEditar);

        txtNombreClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtNombreClienteEditar.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtNombreClienteEditar.setMaximumSize(new java.awt.Dimension(170, 25));
        txtNombreClienteEditar.setMinimumSize(new java.awt.Dimension(170, 25));
        txtNombreClienteEditar.setPreferredSize(new java.awt.Dimension(170, 25));
        panelDatosClienteEditar.add(txtNombreClienteEditar);

        lblApellido1ClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblApellido1ClienteEditar.setText("Apellido 1 corregido");
        lblApellido1ClienteEditar.setMaximumSize(new java.awt.Dimension(150, 20));
        lblApellido1ClienteEditar.setMinimumSize(new java.awt.Dimension(150, 20));
        lblApellido1ClienteEditar.setPreferredSize(new java.awt.Dimension(150, 20));
        panelDatosClienteEditar.add(lblApellido1ClienteEditar);

        txtApellido1ClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtApellido1ClienteEditar.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtApellido1ClienteEditar.setMaximumSize(new java.awt.Dimension(170, 25));
        txtApellido1ClienteEditar.setMinimumSize(new java.awt.Dimension(170, 25));
        txtApellido1ClienteEditar.setPreferredSize(new java.awt.Dimension(170, 25));
        panelDatosClienteEditar.add(txtApellido1ClienteEditar);

        lblApellido2ClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblApellido2ClienteEditar.setText("Apellido 2 corregido");
        lblApellido2ClienteEditar.setMaximumSize(new java.awt.Dimension(150, 20));
        lblApellido2ClienteEditar.setMinimumSize(new java.awt.Dimension(150, 20));
        lblApellido2ClienteEditar.setPreferredSize(new java.awt.Dimension(150, 20));
        panelDatosClienteEditar.add(lblApellido2ClienteEditar);

        txtApellido2ClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtApellido2ClienteEditar.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtApellido2ClienteEditar.setMaximumSize(new java.awt.Dimension(170, 25));
        txtApellido2ClienteEditar.setMinimumSize(new java.awt.Dimension(170, 25));
        txtApellido2ClienteEditar.setPreferredSize(new java.awt.Dimension(170, 25));
        panelDatosClienteEditar.add(txtApellido2ClienteEditar);

        lblTelefonoClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblTelefonoClienteEditar.setText("Teléfono corregido");
        lblTelefonoClienteEditar.setMaximumSize(new java.awt.Dimension(150, 20));
        lblTelefonoClienteEditar.setMinimumSize(new java.awt.Dimension(150, 20));
        lblTelefonoClienteEditar.setPreferredSize(new java.awt.Dimension(150, 20));
        panelDatosClienteEditar.add(lblTelefonoClienteEditar);

        txtTelefonoClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtTelefonoClienteEditar.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtTelefonoClienteEditar.setMaximumSize(new java.awt.Dimension(170, 25));
        txtTelefonoClienteEditar.setMinimumSize(new java.awt.Dimension(170, 25));
        txtTelefonoClienteEditar.setPreferredSize(new java.awt.Dimension(170, 25));
        panelDatosClienteEditar.add(txtTelefonoClienteEditar);

        btnIngresarClienteEditar.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        btnIngresarClienteEditar.setText("INGRESAR");
        btnIngresarClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarClienteEditarActionPerformed(evt);
            }
        });
        panelDatosClienteEditar.add(btnIngresarClienteEditar);

        javax.swing.GroupLayout panelEditarClientesLayout = new javax.swing.GroupLayout(panelEditarClientes);
        panelEditarClientes.setLayout(panelEditarClientesLayout);
        panelEditarClientesLayout.setHorizontalGroup(
            panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarClientesLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(panelDatosClienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        panelEditarClientesLayout.setVerticalGroup(
            panelEditarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarClientesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(panelDatosClienteEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        internalFrameEditarCliente.getContentPane().add(panelEditarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 411));

        jDesktopPane.add(internalFrameEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 700, 470));

        internalFrameEliminarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        internalFrameEliminarCliente.setClosable(true);
        internalFrameEliminarCliente.setTitle("Editar cliente");
        internalFrameEliminarCliente.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cazuela-30.png"))); // NOI18N
        internalFrameEliminarCliente.setMaximumSize(new java.awt.Dimension(720, 472));
        internalFrameEliminarCliente.setMinimumSize(new java.awt.Dimension(720, 472));
        internalFrameEliminarCliente.setPreferredSize(new java.awt.Dimension(720, 472));
        internalFrameEliminarCliente.setVisible(true);
        internalFrameEliminarCliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEliminarClientes.setMaximumSize(new java.awt.Dimension(700, 440));
        panelEliminarClientes.setMinimumSize(new java.awt.Dimension(700, 440));

        panelEliminarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEliminarCliente.setMaximumSize(new java.awt.Dimension(400, 300));
        panelEliminarCliente.setMinimumSize(new java.awt.Dimension(400, 300));
        panelEliminarCliente.setPreferredSize(new java.awt.Dimension(400, 300));
        panelEliminarCliente.setRequestFocusEnabled(false);
        panelEliminarCliente.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lblDatosClienteEliminar.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblDatosClienteEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatosClienteEliminar.setText("DATOS DEL CLIENTE A ELIMINAR");
        lblDatosClienteEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDatosClienteEliminar.setMaximumSize(new java.awt.Dimension(320, 24));
        lblDatosClienteEliminar.setMinimumSize(new java.awt.Dimension(320, 24));
        lblDatosClienteEliminar.setPreferredSize(new java.awt.Dimension(320, 24));
        panelEliminarCliente.add(lblDatosClienteEliminar);

        lblUsuarioClienteEliminar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblUsuarioClienteEliminar.setText("Usuario");
        lblUsuarioClienteEliminar.setMaximumSize(new java.awt.Dimension(150, 20));
        lblUsuarioClienteEliminar.setMinimumSize(new java.awt.Dimension(150, 20));
        lblUsuarioClienteEliminar.setPreferredSize(new java.awt.Dimension(150, 20));
        panelEliminarCliente.add(lblUsuarioClienteEliminar);

        txtUsuarioClienteEliminar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtUsuarioClienteEliminar.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtUsuarioClienteEliminar.setMaximumSize(new java.awt.Dimension(170, 25));
        txtUsuarioClienteEliminar.setMinimumSize(new java.awt.Dimension(170, 25));
        txtUsuarioClienteEliminar.setPreferredSize(new java.awt.Dimension(170, 25));
        panelEliminarCliente.add(txtUsuarioClienteEliminar);

        lblNombreClienteEliminar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblNombreClienteEliminar.setText("Nombre ");
        lblNombreClienteEliminar.setMaximumSize(new java.awt.Dimension(150, 20));
        lblNombreClienteEliminar.setMinimumSize(new java.awt.Dimension(150, 20));
        lblNombreClienteEliminar.setPreferredSize(new java.awt.Dimension(150, 20));
        panelEliminarCliente.add(lblNombreClienteEliminar);

        txtNombreClienteEliminar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtNombreClienteEliminar.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtNombreClienteEliminar.setMaximumSize(new java.awt.Dimension(170, 25));
        txtNombreClienteEliminar.setMinimumSize(new java.awt.Dimension(170, 25));
        txtNombreClienteEliminar.setPreferredSize(new java.awt.Dimension(170, 25));
        panelEliminarCliente.add(txtNombreClienteEliminar);

        lblApellido1ClienteEliminar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblApellido1ClienteEliminar.setText("Apellido 1");
        lblApellido1ClienteEliminar.setMaximumSize(new java.awt.Dimension(150, 20));
        lblApellido1ClienteEliminar.setMinimumSize(new java.awt.Dimension(150, 20));
        lblApellido1ClienteEliminar.setPreferredSize(new java.awt.Dimension(150, 20));
        panelEliminarCliente.add(lblApellido1ClienteEliminar);

        txtApellido1ClienteEliminar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtApellido1ClienteEliminar.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtApellido1ClienteEliminar.setMaximumSize(new java.awt.Dimension(170, 25));
        txtApellido1ClienteEliminar.setMinimumSize(new java.awt.Dimension(170, 25));
        txtApellido1ClienteEliminar.setPreferredSize(new java.awt.Dimension(170, 25));
        panelEliminarCliente.add(txtApellido1ClienteEliminar);

        lblApellido2ClienteEliminar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblApellido2ClienteEliminar.setText("Apellido 2");
        lblApellido2ClienteEliminar.setMaximumSize(new java.awt.Dimension(150, 20));
        lblApellido2ClienteEliminar.setMinimumSize(new java.awt.Dimension(150, 20));
        lblApellido2ClienteEliminar.setPreferredSize(new java.awt.Dimension(150, 20));
        panelEliminarCliente.add(lblApellido2ClienteEliminar);

        txtApellido2ClienteEliminar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtApellido2ClienteEliminar.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtApellido2ClienteEliminar.setMaximumSize(new java.awt.Dimension(170, 25));
        txtApellido2ClienteEliminar.setMinimumSize(new java.awt.Dimension(170, 25));
        txtApellido2ClienteEliminar.setPreferredSize(new java.awt.Dimension(170, 25));
        panelEliminarCliente.add(txtApellido2ClienteEliminar);

        lblTelefonoClienteEliminar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        lblTelefonoClienteEliminar.setText("Teléfono");
        lblTelefonoClienteEliminar.setMaximumSize(new java.awt.Dimension(150, 20));
        lblTelefonoClienteEliminar.setMinimumSize(new java.awt.Dimension(150, 20));
        lblTelefonoClienteEliminar.setPreferredSize(new java.awt.Dimension(150, 20));
        panelEliminarCliente.add(lblTelefonoClienteEliminar);

        txtTelefonoClienteEliminar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txtTelefonoClienteEliminar.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtTelefonoClienteEliminar.setMaximumSize(new java.awt.Dimension(170, 25));
        txtTelefonoClienteEliminar.setMinimumSize(new java.awt.Dimension(170, 25));
        txtTelefonoClienteEliminar.setPreferredSize(new java.awt.Dimension(170, 25));
        panelEliminarCliente.add(txtTelefonoClienteEliminar);

        btnEliminarCliente.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        btnEliminarCliente.setText("ELIMINAR");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        panelEliminarCliente.add(btnEliminarCliente);

        javax.swing.GroupLayout panelEliminarClientesLayout = new javax.swing.GroupLayout(panelEliminarClientes);
        panelEliminarClientes.setLayout(panelEliminarClientesLayout);
        panelEliminarClientesLayout.setHorizontalGroup(
            panelEliminarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarClientesLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(panelEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        panelEliminarClientesLayout.setVerticalGroup(
            panelEliminarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarClientesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(panelEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        internalFrameEliminarCliente.getContentPane().add(panelEliminarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 411));

        jDesktopPane.add(internalFrameEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        getContentPane().add(jDesktopPane, java.awt.BorderLayout.PAGE_START);

        mnuBVentanaGestionEmpleados.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        mnuBVentanaGestionEmpleados.setMargin(new java.awt.Insets(5, 5, 5, 5));
        mnuBVentanaGestionEmpleados.setMaximumSize(new java.awt.Dimension(100, 60));
        mnuBVentanaGestionEmpleados.setMinimumSize(new java.awt.Dimension(100, 60));
        mnuBVentanaGestionEmpleados.setPreferredSize(new java.awt.Dimension(100, 60));

        mnuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubiertos 40.png"))); // NOI18N
        mnuProductos.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        mnuProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuProductos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        mnuProductos.setIconTextGap(10);
        mnuProductos.setLabel("Productos");
        mnuProductos.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mnuProductos.setMaximumSize(new java.awt.Dimension(200, 60));
        mnuProductos.setMinimumSize(new java.awt.Dimension(200, 60));
        mnuProductos.setPreferredSize(new java.awt.Dimension(200, 60));

        mnuIProductosEnVenta.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        mnuIProductosEnVenta.setLabel("Productos en venta");
        mnuIProductosEnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIProductosEnVentaActionPerformed(evt);
            }
        });
        mnuProductos.add(mnuIProductosEnVenta);

        mnuBVentanaGestionEmpleados.add(mnuProductos);

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes 40.png"))); // NOI18N
        mnuClientes.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        mnuClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuClientes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        mnuClientes.setIconTextGap(10);
        mnuClientes.setLabel("Clientes");
        mnuClientes.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mnuClientes.setMaximumSize(new java.awt.Dimension(170, 60));
        mnuClientes.setMinimumSize(new java.awt.Dimension(170, 60));
        mnuClientes.setPreferredSize(new java.awt.Dimension(170, 60));

        mnuIClientesRegistrados.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        mnuIClientesRegistrados.setText("Clientes registrados");
        mnuIClientesRegistrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIClientesRegistradosActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuIClientesRegistrados);

        mnuIRegistrarNuevoCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        mnuIRegistrarNuevoCliente.setText("Registrar nuevo cliente");
        mnuIRegistrarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIRegistrarNuevoClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuIRegistrarNuevoCliente);

        mnuIModificarCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        mnuIModificarCliente.setText("Modificar cliente");
        mnuIModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIModificarClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuIModificarCliente);

        mnuIEliminarCliente.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        mnuIEliminarCliente.setText("Eliminar cliente");
        mnuIEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIEliminarClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuIEliminarCliente);

        mnuBVentanaGestionEmpleados.add(mnuClientes);

        mnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/euro 40.png"))); // NOI18N
        mnuVentas.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        mnuVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuVentas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        mnuVentas.setIconTextGap(10);
        mnuVentas.setLabel("Ventas");
        mnuVentas.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mnuVentas.setMaximumSize(new java.awt.Dimension(160, 60));
        mnuVentas.setMinimumSize(new java.awt.Dimension(160, 60));
        mnuVentas.setPreferredSize(new java.awt.Dimension(160, 60));

        mnuIVentasPorDia.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        mnuIVentasPorDia.setText("Ventas por día");
        mnuIVentasPorDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIVentasPorDiaActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuIVentasPorDia);

        mnuIVentasTotales.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        mnuIVentasTotales.setText("Ventas totales");
        mnuIVentasTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIVentasTotalesActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuIVentasTotales);

        mnuBVentanaGestionEmpleados.add(mnuVentas);

        mnuMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu fino 40.png"))); // NOI18N
        mnuMenu.setText("Menu");
        mnuMenu.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        mnuMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuMenu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        mnuMenu.setIconTextGap(10);
        mnuMenu.setMargin(new java.awt.Insets(10, 10, 10, 10));
        mnuMenu.setMaximumSize(new java.awt.Dimension(170, 60));
        mnuMenu.setMinimumSize(new java.awt.Dimension(170, 60));
        mnuMenu.setPreferredSize(new java.awt.Dimension(170, 60));

        mnuIVentanaIngreso.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        mnuIVentanaIngreso.setText("Ventana ingreso");
        mnuIVentanaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIVentanaIngresoActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuIVentanaIngreso);

        mnuISalir.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        mnuISalir.setText("Salir");
        mnuISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuISalirActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuISalir);

        mnuBVentanaGestionEmpleados.add(mnuMenu);

        setJMenuBar(mnuBVentanaGestionEmpleados);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuIProductosEnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIProductosEnVentaActionPerformed
        
        /**Todo esto tendría que ir en ConsultaEmpleadosDAO, y ser llamado desde
         * ControladorEmpleadosDAO, pero al ser JTable y trabajar con DefaultTableModel, 
         * me encontré con dificultades y no pude organizarlo de esa manera.
        */
        
        int numeroColumnas = 4;
        
        String [] nombreColumnas = new String[numeroColumnas];
        nombreColumnas[0] = "Código Producto";
        nombreColumnas[1] = "Nombre Producto";
        nombreColumnas[2] = "Precio Producto";
        nombreColumnas[3] = "Alias Producto";
        
        String instruccionSQL = "select codigoproducto,nombreproducto,precioproducto,aliasproducto from productoscazuela";
                
        formatoTextoColumnas(tablaProductosEnVenta);
        mostrarTabla(tablaProductosEnVenta,numeroColumnas,nombreColumnas,instruccionSQL,internalFrameTablaProductosEnVenta);
        
    }//GEN-LAST:event_mnuIProductosEnVentaActionPerformed

    private void mnuIClientesRegistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIClientesRegistradosActionPerformed
        
        int numeroColumnas = 6;
        
        String [] nombreColumnas = new String[numeroColumnas];
        nombreColumnas[0] = "ID Cliente";
        nombreColumnas[1] = "Nombre";
        nombreColumnas[2] = "Apellido 1";
        nombreColumnas[3] = "Apellido 2";
        nombreColumnas[4] = "Teléfono";
        nombreColumnas[5] = "Usuario";
        
        String instruccionSQL = "select idcliente,nombre,apellido1,apellido2,telefono,usuario from clientescazuela";
                
        formatoTextoColumnas(tablaClientesRegistrados);
        mostrarTabla(tablaClientesRegistrados,numeroColumnas,nombreColumnas,instruccionSQL,internalFrameClientesRegistrados);
        
    }//GEN-LAST:event_mnuIClientesRegistradosActionPerformed

    private void mnuIVentasPorDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIVentasPorDiaActionPerformed
       cargarJComboBoxFechasVentas();       
       internalFrameVentasPorDiaJComboBox.setVisible(true);
    }//GEN-LAST:event_mnuIVentasPorDiaActionPerformed

    private void mnuIVentasTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIVentasTotalesActionPerformed
    
    int numeroColumnas = 5;
    String [] nombreColumnas = new String[numeroColumnas];
    nombreColumnas[0] = "IDVenta";
    nombreColumnas[1] = "Nombre Producto";
    nombreColumnas[2] = "Precio Producto";
    nombreColumnas[3] = "Alias Producto";
    nombreColumnas[4] = "Fecha";

        
    String instruccionSQL = "select idventa,nombreproducto,precioproducto,aliasproducto,fecha from ventascazuela";
                
        formatoTextoColumnas(tablaVentasTotales);
        mostrarTabla(tablaVentasTotales,numeroColumnas,nombreColumnas,instruccionSQL,internalFrameVentasTotales);
    }//GEN-LAST:event_mnuIVentasTotalesActionPerformed

    private void mnuIVentanaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIVentanaIngresoActionPerformed
        controladorConsultaEmpleados.actionPerformed(evt);
    }//GEN-LAST:event_mnuIVentanaIngresoActionPerformed

    private void mnuISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuISalirActionPerformed
        controladorConsultaEmpleados.actionPerformed(evt);
    }//GEN-LAST:event_mnuISalirActionPerformed

    private void mnuIRegistrarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIRegistrarNuevoClienteActionPerformed
        internalFrameInsertarCliente.setVisible(true);
    }//GEN-LAST:event_mnuIRegistrarNuevoClienteActionPerformed

    private void btnIngresarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarNuevoClienteActionPerformed
        controladorConsultaEmpleados.actionPerformed(evt);
    }//GEN-LAST:event_btnIngresarNuevoClienteActionPerformed

    private void btnObtenerUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerUsuarioActionPerformed
        String usuario = (((this.txtNombreNuevoCliente.getText())+(this.txtApellido1NuevoCliente.getText())).toLowerCase());
        this.txtUsuarioNuevoCliente.setText(usuario);
        txtUsuarioNuevoCliente.setVisible(true);
    }//GEN-LAST:event_btnObtenerUsuarioActionPerformed

    private void jComboBoxFechasVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFechasVentasActionPerformed

        String fecha = (String) jComboBoxFechasVentas.getSelectedItem();        

        this.internalFrameVentasPorDiaJComboBox.setVisible(false);

        int numeroColumnas = 5;
        String [] nombreColumnas = new String[numeroColumnas];
        nombreColumnas[0] = "IDVenta";
        nombreColumnas[1] = "Nombre Producto";
        nombreColumnas[2] = "Precio Producto";
        nombreColumnas[3] = "Alias Producto";
        nombreColumnas[4] = "Fecha";

        String instruccionSQL = "select idventa,nombreproducto,precioproducto,aliasproducto,fecha from ventascazuela where fecha = '"+fecha+"'";

        formatoTextoColumnas(tablaVentasPorDia);
        mostrarTabla(tablaVentasPorDia,numeroColumnas,nombreColumnas,instruccionSQL,internalFrameVentasPorDiaTabla);

    }//GEN-LAST:event_jComboBoxFechasVentasActionPerformed

    private void mnuIModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIModificarClienteActionPerformed
        this.internalFrameEditarCliente.setVisible(true);
    }//GEN-LAST:event_mnuIModificarClienteActionPerformed

    private void mnuIEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIEliminarClienteActionPerformed
        this.internalFrameEliminarCliente.setVisible(true);
    }//GEN-LAST:event_mnuIEliminarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        controladorConsultaEmpleados.actionPerformed(evt);
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnIngresarClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarClienteEditarActionPerformed
        controladorConsultaEmpleados.actionPerformed(evt);
    }//GEN-LAST:event_btnIngresarClienteEditarActionPerformed

    /**
     * 
     * @param tabla Tabla donde se mostrarán los datos extraídos de la base de datos
     * @param cantidadColumnas Cantidad de columnas que tiene la tabla
     * @param nombreColumnas Nombre de las columnas
     * @param instruccionSQL Instrucción SQL que se ejecutará en la consulta a base de datos
     * @param internalFrame InternalFrame contenedor
     */
    
    public void mostrarTabla(JTable tabla, int cantidadColumnas, String[] nombreColumnas, String instruccionSQL, JInternalFrame internalFrame){
        
        ConexionBBDD conexionBBDD = new ConexionBBDD ();
        Connection miConexion;
        
        DefaultTableModel modeloTabla = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };
        
        tabla.setModel(modeloTabla);        
 
        PreparedStatement ps=null;
        ResultSet rs=null;
        
        try{
            miConexion=conexionBBDD.conectar();            
            ps = miConexion.prepareStatement(instruccionSQL);
            rs = ps.executeQuery();
            
            for(int j=0;j<cantidadColumnas;j++){
                modeloTabla.addColumn(nombreColumnas[j]);
            }
            
            while(rs.next()){//Mientras siga habiendo registros en la BBDD
                Object fila[]= new Object[cantidadColumnas];
                for(int i=0;i<cantidadColumnas;i++){
                    fila[i] = rs.getObject(i+1); //Guardo cada fila en un arreglo                                        
                }
                modeloTabla.addRow(fila);
            }
        }catch(Exception e){
            e.printStackTrace();            
        }
        internalFrame.setVisible(true);
    }
    
    /**
     * Método que da formato al encabezado de las columnas de la tabla
     * @param tabla donde se mostrarán los datos extraídos de la base de datos
     */
    public void formatoTextoColumnas(JTable tabla){
        JTableHeader th;
        th = tabla.getTableHeader();
        Font fuente = new Font("Sylfaen",Font.BOLD,14);
        th.setFont(fuente);
    }
    
    /**
     * Método que carga en un JComboBox las fechas de las ventas registradas
     */
    public void cargarJComboBoxFechasVentas(){
        ConexionBBDD conexionBBDD = new ConexionBBDD ();
        Connection miConexion;                
            
        PreparedStatement ps=null;
        ResultSet rs=null;
        
        jComboBoxFechasVentas.addItem("Elegir fecha");
        try{
            miConexion=conexionBBDD.conectar();            
            ps = miConexion.prepareStatement("select distinct fecha from ventascazuela");
            rs = ps.executeQuery();
            while(rs.next()){
                jComboBoxFechasVentas.addItem(rs.getString("fecha"));
            }
            rs.close();
            
        }catch(Exception e){
            e.printStackTrace();            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultaEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminarCliente;
    public javax.swing.JButton btnIngresarClienteEditar;
    public javax.swing.JButton btnIngresarNuevoCliente;
    public javax.swing.JButton btnObtenerUsuario;
    private javax.swing.JInternalFrame internalFrameClientesRegistrados;
    private javax.swing.JInternalFrame internalFrameEditarCliente;
    private javax.swing.JInternalFrame internalFrameEliminarCliente;
    private javax.swing.JInternalFrame internalFrameInsertarCliente;
    private javax.swing.JInternalFrame internalFrameTablaProductosEnVenta;
    private javax.swing.JInternalFrame internalFrameVentasPorDiaJComboBox;
    private javax.swing.JInternalFrame internalFrameVentasPorDiaTabla;
    private javax.swing.JInternalFrame internalFrameVentasTotales;
    public javax.swing.JComboBox<String> jComboBoxFechasVentas;
    private javax.swing.JDesktopPane jDesktopPane;
    public javax.swing.JLabel lblApellido1ClienteEditar;
    public javax.swing.JLabel lblApellido1ClienteEliminar;
    public javax.swing.JLabel lblApellido1NuevoCliente;
    private javax.swing.JLabel lblApellido2ClienteEditar;
    private javax.swing.JLabel lblApellido2ClienteEliminar;
    private javax.swing.JLabel lblApellido2NuevoCliente;
    private javax.swing.JLabel lblDatosClienteEditar;
    private javax.swing.JLabel lblDatosClienteEliminar;
    private javax.swing.JLabel lblDatosNuevoCliente;
    public javax.swing.JLabel lblFechas;
    public javax.swing.JLabel lblNombreClienteEditar;
    public javax.swing.JLabel lblNombreClienteEliminar;
    public javax.swing.JLabel lblNombreNuevoCliente;
    private javax.swing.JLabel lblTelefonoClienteEditar;
    private javax.swing.JLabel lblTelefonoClienteEliminar;
    private javax.swing.JLabel lblTelefonoNuevoCliente;
    private javax.swing.JLabel lblUsuarioClienteEditar;
    private javax.swing.JLabel lblUsuarioClienteEliminar;
    private javax.swing.JLabel lblUsuarioNuevoCliente;
    private javax.swing.JMenuBar mnuBVentanaGestionEmpleados;
    public javax.swing.JMenu mnuClientes;
    public javax.swing.JMenuItem mnuIClientesRegistrados;
    public javax.swing.JMenuItem mnuIEliminarCliente;
    public javax.swing.JMenuItem mnuIModificarCliente;
    public javax.swing.JMenuItem mnuIProductosEnVenta;
    private javax.swing.JMenuItem mnuIRegistrarNuevoCliente;
    public javax.swing.JMenuItem mnuISalir;
    public javax.swing.JMenuItem mnuIVentanaIngreso;
    public javax.swing.JMenuItem mnuIVentasPorDia;
    public javax.swing.JMenuItem mnuIVentasTotales;
    public javax.swing.JMenu mnuMenu;
    public javax.swing.JMenu mnuProductos;
    public javax.swing.JMenu mnuVentas;
    private javax.swing.JPanel panelDatosClienteEditar;
    private javax.swing.JPanel panelDatosNuevoCliente;
    public javax.swing.JPanel panelEditarClientes;
    private javax.swing.JPanel panelEliminarCliente;
    public javax.swing.JPanel panelEliminarClientes;
    public javax.swing.JPanel panelInsertarClientes;
    public javax.swing.JScrollPane panelScrollTablaClientesRegistrados;
    public javax.swing.JScrollPane panelScrollTablaProductosEnVenta;
    public javax.swing.JScrollPane panelScrollTablaVentasPorDiaTabla;
    public javax.swing.JScrollPane panelScrollTablaVentasTotales;
    public javax.swing.JPanel panelTablaClientesRegistrados;
    public javax.swing.JPanel panelTablaProductosEnVenta;
    public javax.swing.JPanel panelTablaVentasPorDiaTabla;
    public javax.swing.JPanel panelTablaVentasTotales;
    public javax.swing.JPanel panelVentasPorDiaJComboBox;
    public javax.swing.JTable tablaClientesRegistrados;
    public javax.swing.JTable tablaProductosEnVenta;
    public javax.swing.JTable tablaVentasPorDia;
    public javax.swing.JTable tablaVentasTotales;
    public javax.swing.JTextField txtApellido1ClienteEditar;
    public javax.swing.JTextField txtApellido1ClienteEliminar;
    public javax.swing.JTextField txtApellido1NuevoCliente;
    public javax.swing.JTextField txtApellido2ClienteEditar;
    public javax.swing.JTextField txtApellido2ClienteEliminar;
    public javax.swing.JTextField txtApellido2NuevoCliente;
    public javax.swing.JTextField txtNombreClienteEditar;
    public javax.swing.JTextField txtNombreClienteEliminar;
    public javax.swing.JTextField txtNombreNuevoCliente;
    public javax.swing.JTextField txtTelefonoClienteEditar;
    public javax.swing.JTextField txtTelefonoClienteEliminar;
    public javax.swing.JTextField txtTelefonoNuevoCliente;
    public javax.swing.JTextField txtUsuarioClienteEditar;
    public javax.swing.JTextField txtUsuarioClienteEliminar;
    public javax.swing.JTextField txtUsuarioNuevoCliente;
    // End of variables declaration//GEN-END:variables
}
